﻿apiVersion: v1
kind: Namespace
metadata:
  name: example
  labels:
    name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: fortunen/finecontroller-csharp-example-01
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example
  labels:
    app: example
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: example
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /example(/|$)(.*)
        backend:
          service:
            name: example
            port:
              number: 80
---