apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{service-name}}
  namespace: {{service-namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /{{service-name}}(/|$)(.*)
        backend:
          service:
            name: {{service-name}}
            port:
              number: {{service-port}}