name: mac-test
on:
  workflow_dispatch:
jobs:
  build:
    name: mac-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up cache for Homebrew downloads
        id: cache-homebrew-downloads
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/Homebrew/downloads
          key: ${{ runner.os }}-homebrew-downloads-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-downloads-

      - name: Install Docker Desktop
        if: steps.cache-homebrew-downloads.outputs.cache-hit != 'true'
        run: brew install --cask docker

      - name: Start Docker Desktop
        run: |
          open --background -a /Applications/Docker.app

      - name: Wait for Docker to be running
        run: |
          timeout=600
          interval=10
          while [ $timeout -gt 0 ]; do
            docker info >/dev/null 2>&1 && break
            echo "Waiting for Docker to be running..."
            sleep $interval
            timeout=$((timeout - interval))
          done
          if [ $timeout -le 0 ]; then
            echo "Docker did not start within 10 minutes. Exiting."
            exit 1
          fi
          
      - name: Run
        run: cd Application && dotnet run --project 30.Application.csproj
