name: mac-test
on:
  workflow_dispatch:
jobs:
  build:
    name: mac-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: brew install --cask docker
      - run:
          until cat missingfile
          do
              echo waiting for missingfile
              sleep 10
          done
      - run: cd Application && dotnet run --project 30.Application.csproj
