name: mac-test
on:
  workflow_dispatch:
jobs:
  build:
    name: mac-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: brew install --cask docker
      - run: while ! docker ps > /dev/null 2>&1; do echo "Waiting for Docker..."; sleep 5; done; echo "Docker is ready."
      - run: cd Application && dotnet run --project 30.Application.csproj
